//
//  SVG.swift
//  LaTeXSwiftUI
//
//  Copyright (c) 2023 Colin Campbell
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to
//  deal in the Software without restriction, including without limitation the
//  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
//  sell copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
//  IN THE SOFTWARE.
//

import Foundation

/// Contains SVG information.
internal struct SVG: Codable, Hashable, Sendable {
  
  /// An error produced when creating an SVG.
  enum SVGError: Error, Sendable {
    case encodingSVGData
  }
  
  /// The SVG's data.
  let data: Data
  
  /// The SVG's geometry.
  let geometry: SVGGeometry
  
  /// Any error text produced when creating the SVG.
  let errorText: String?

  /// Speech text generated by the Speech Rule Engine for accessibility.
  let speechText: String?
  
  // MARK: Initializers
  
  /// Initializes a new SVG from data.
  ///
  /// - Parameter data: The SVG data.
  init(data: Data) throws {
    self = try JSONDecoder().decode(Self.self, from: data)
  }
  
  // MARK: Precompiled regex patterns

  private nonisolated static let dataAttrRegex = try! NSRegularExpression(pattern: #"(data-\w+=")((?:[^"\\]|\\.)*)(")"#)
  private nonisolated static let dataLineRegex = try! NSRegularExpression(pattern: #"(<line\b[^>]*\bdata-line\b[^>]*?)(\/?>)"#)
  private nonisolated static let borderLineRegex = try! NSRegularExpression(pattern: #"(<line\b(?![^>]*\bdata-line\b)(?![^>]*\bstroke=")[^>]*?\bstroke-width="[^"]*"[^>]*?)(\/?>)"#)
  private nonisolated static let dataFrameRegex = try! NSRegularExpression(pattern: #"(<rect\b[^>]*\bdata-frame\b(?![^>]*\bstroke=")[^>]*?)(\/?>)"#)

  /// Initializes a new SVG.
  ///
  /// - Parameters:
  ///   - svgString: The SVG's input string.
  ///   - errorText: The error text that was generated when creating the SVG.
  init(svgString: String, errorText: String? = nil, speechText: String? = nil) throws {
    self.errorText = errorText
    self.speechText = speechText

    // Fix invalid XML: MathJax emits unescaped `<` and `>` in
    // `data-latex` attribute values (e.g. `data-latex="x < 0"`).
    // These must be escaped for SwiftDraw's XML parser.
    let escapedSVG = Self.escapeDataAttributes(svgString)

    // Patch SVG elements that rely on CSS for stroke styling.
    // SwiftDraw doesn't apply CSS stylesheets, so we inline the
    // stroke attributes that MathJax's CSS would normally provide
    // for array borders and horizontal rules.
    let patchedSVG = Self.patchStrokeAttributes(escapedSVG)

    // Get the SVG's geometry
    geometry = try SVGGeometry(svg: patchedSVG)

    // Get the SVG data
    if let svgData = patchedSVG.data(using: .utf8) {
      data = svgData
    }
    else {
      throw SVGError.encodingSVGData
    }
  }
  
}

// MARK: Methods

extension SVG {
  
  /// The JSON encoded value of the receiver.
  ///
  /// - Returns: The receivers JSON encoded data.
  func encoded() throws -> Data {
    try JSONEncoder().encode(self)
  }
  
  /// Escapes invalid XML characters in `data-*` attribute values.
  ///
  /// MathJax v4 emits `data-latex` attributes containing the raw TeX
  /// input, which may include `<` and `>` characters (e.g.
  /// `data-latex="x < 0"`). These are invalid in XML attribute values
  /// and cause SwiftDraw's XML parser to fail. This method escapes
  /// them to `&lt;` and `&gt;`.
  private static func escapeDataAttributes(_ svgString: String) -> String {
    let mutable = NSMutableString(string: svgString)
    let matches = dataAttrRegex.matches(in: svgString, range: NSRange(location: 0, length: mutable.length))
    // Process in reverse to maintain range validity
    for match in matches.reversed() {
      let valueRange = match.range(at: 2)
      let value = mutable.substring(with: valueRange)
      if value.contains("<") || value.contains(">") {
        let escaped = value
          .replacingOccurrences(of: "&", with: "&amp;")
          .replacingOccurrences(of: "<", with: "&lt;")
          .replacingOccurrences(of: ">", with: "&gt;")
        mutable.replaceCharacters(in: valueRange, with: escaped)
      }
    }
    return mutable as String
  }

  /// Patches SVG elements that rely on MathJax CSS for stroke styling.
  ///
  /// MathJax renders array borders and horizontal rules using `<line>` and
  /// `<rect>` elements with `data-frame` or `data-line` attributes. These
  /// elements depend on a CSS rule for their appearance:
  ///
  ///     [data-frame],[data-line]{stroke-width:70px;fill:none}
  ///
  /// SwiftDraw does not apply CSS stylesheets, so these elements render
  /// invisibly. This method inlines the stroke attributes directly onto
  /// the affected elements.
  ///
  /// - Parameter svgString: The raw SVG string from MathJax.
  /// - Returns: The patched SVG string.
  private static func patchStrokeAttributes(_ svgString: String) -> String {
    var result = svgString

    // Inline stroke on <line data-line> (array separators/rules)
    result = replaceAll(dataLineRegex, in: result, template: ##"$1 stroke="#000" stroke-width="70" $2"##)

    // Inline stroke on border <line> elements (have stroke-width but no stroke color)
    result = replaceAll(borderLineRegex, in: result, template: ##"$1 stroke="#000" $2"##)

    // Inline stroke on <rect data-frame> (table borders)
    result = replaceAll(dataFrameRegex, in: result, template: ##"$1 stroke="#000" stroke-width="70" fill="none" $2"##)

    return result
  }

  /// Applies a regex replacement to all matches in a string.
  private static func replaceAll(_ regex: NSRegularExpression, in string: String, template: String) -> String {
    let mutable = NSMutableString(string: string)
    regex.replaceMatches(in: mutable, range: NSRange(location: 0, length: mutable.length), withTemplate: template)
    return mutable as String
  }

  /// The size of the SVG based on the current font's x-height.
  ///
  /// - Parameter xHeight: The font's x-height.
  /// - Returns: A size.
  func size(for xHeight: CGFloat) -> CGSize {
    CGSize(
      width: geometry.width.toPoints(xHeight),
      height: geometry.height.toPoints(xHeight)
    )
  }
  
}
